#!/bin/bash

# OpenCV 4.6.0 ArUco 버그 해결 - 안정 버전으로 다운그레이드

echo "=== OpenCV ArUco 문제 해결 가이드 ==="
echo "현재 OpenCV 4.6.0에서 detectMarkers() 함수에 치명적 버그 발견"
echo ""

echo "해결책 1: OpenCV 4.5.x로 다운그레이드 (권장)"
echo "sudo apt remove libopencv-dev libopencv-contrib-dev"
echo "sudo apt autoremove"
echo ""
echo "# OpenCV 4.5.5 설치"
echo "wget -O opencv.zip https://github.com/opencv/opencv/archive/4.5.5.zip"
echo "wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.5.zip"
echo "unzip opencv.zip && unzip opencv_contrib.zip"
echo ""
echo "cd opencv-4.5.5"
echo "mkdir build && cd build"
echo ""
echo "cmake -D CMAKE_BUILD_TYPE=RELEASE \\"
echo "      -D CMAKE_INSTALL_PREFIX=/usr/local \\"
echo "      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.5.5/modules \\"
echo "      -D ENABLE_NEON=ON \\"
echo "      -D OPENCV_ENABLE_NONFREE=ON \\"
echo "      -D BUILD_TESTS=OFF \\"
echo "      -D BUILD_PERF_TESTS=OFF \\"
echo "      -D BUILD_EXAMPLES=OFF \\"
echo "      -D CMAKE_BUILD_WITH_INSTALL_RPATH=ON .."
echo ""
echo "make -j4"
echo "sudo make install"
echo "sudo ldconfig"
echo ""

echo "해결책 2: pip로 안정 버전 설치"
echo "pip3 uninstall opencv-python opencv-contrib-python"
echo "pip3 install opencv-python==4.5.5.64 opencv-contrib-python==4.5.5.64"
echo ""

echo "해결책 3: conda 사용"
echo "conda install -c conda-forge opencv=4.5.5"
echo ""

echo "확인 방법:"
echo "python3 -c \"import cv2; print('OpenCV:', cv2.__version__)\""
echo ""

echo "=== 임시 회피책 ==="
echo "ArUco 사용을 포기하고 색상 마커 시스템 사용:"
echo "python3 simple_marker_detection.py"
echo "python3 detect_aruco_safe.py"
